modLoader="javafml"
loaderVersion="[47,)"
license="${license}"
showAsResourcePack=false
issueTrackerURL="https://github.com/${github}/issues"

[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
authors="${author}, ${contributor}"
logoFile="assets/${namespace}/textures/mod_logo.png"
displayURL="https://github.com/${github}"
displayTest="IGNORE_ALL_VERSION"
features={java_version="[${java_version},)"}
description='''${description}'''

[[mixins]]
config="mixins.${namespace}.forge.json"

[[dependencies."${id}"]]
modId="minecraft"
mandatory=true
versionRange="${minecraft}"
ordering="NONE"
side="CLIENT"

[[dependencies."${id}"]]
modId="embeddium"
mandatory=true
versionRange="${renderer}"
ordering="AFTER"
side="CLIENT"
