modLoader="javafml"
loaderVersion="[1,)"
license="${license}"
showAsResourcePack=false
issueTrackerURL="https://github.com/${github}/issues"

[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
authors="${author}, ${contributor}"
logoFile="assets/${namespace}/textures/mod_logo.png"
displayURL="https://github.com/${github}"
displayTest="IGNORE_ALL_VERSION"
description='''${description}'''

[[mixins]]
config="mixins.${namespace}.json"

[features.${id}]
javaVersion="[${java_version},)"

[[dependencies."${id}"]]
modId="minecraft"
type="required"
versionRange="${minecraft}"
ordering="NONE"
side="CLIENT"

[[dependencies."${id}"]]
modId="embeddium"
type="required"
versionRange="${renderer}"
ordering="AFTER"
side="CLIENT"
